---
title: "ECB Biological rhythms &  timing of protein-protein interactions Project"
author: "Hannah Chu"
date: "2018-06-15"
output:
  prettydoc::html_pretty:
    theme: cayman
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
fontsize: 18pt
---
# Library
```{r}
library(DiagrammeR)
```

# Setup
* 5 Cohorts:
  * 10 female UZ individuals - 5 RT & 5 SO
  * 10 female BE individuals - 5 RT & 5 SO
  * 10 male UZ individuals - 5 RT & 5 SO
  * 10 male BE individuals - 5 RT & 5 SO

# Overall Workflow

```{r}
mermaid("
  graph TD
  A[Cohort Day] --separate eggs--> B[SO diapause]
  A --separate eggs--> C[RT direct development]
  B --5 females UZ & BE and 5 males UZ & BE--> D[46 days, 23ºC, 12L:12D until pupation]
  C --5 females UZ & BE and 5 males UZ & BE--> E[46 days, 23ºC, 16L:8D]
  E --transfer--> F[Diapause termination: 26ºC, 16L:8D until pupation]
  F --eclosion--> G[move adults to Trikinetics in Free Run conditions]
  D --> E")
```

# Session Info
```{r}
sessionInfo()
```